#pragma once

#include <stdint.h>
#include <stdbool.h>

#include "conf.h"

/*
use this for things like enumerations, structures
*/

#define RESET_MAGIC    0x51A7C0DE

#define WAV_RIFF_HEADER_LENGTH 44
#define WAV_ENCRYPTED_CHUNK_NONCE_LENGTH RECORDER_ENCRYPTED_CHUNK_NONCE_LENGTH
#define WAV_ENCRYPTED_CHUNK_TAG_LENGTH RECORDER_ENCRYPTED_CHUNK_TAG_LENGTH
#define WAV_ENCRYPTED_AUDIO_CHUNK_LENGTH (WAV_ENCRYPTED_CHUNK_NONCE_LENGTH + WAV_ENCRYPTED_AUDIO_PLAINTEXT_LENGTH + WAV_ENCRYPTED_CHUNK_TAG_LENGTH)
#define WAV_ENCRYPTED_RIFF_HEADER_LENGTH (WAV_ENCRYPTED_CHUNK_NONCE_LENGTH + WAV_RIFF_HEADER_LENGTH + WAV_ENCRYPTED_CHUNK_TAG_LENGTH)

#define MP3_PCM_FRAMES_PER_CHUNK             (MP3_PCM_FRAMES_PER_MP3_FRAME * MP3_FRAMES_PER_CHUNK)
#define MP3_PCM_BYTES_PER_CHUNK              (MP3_PCM_FRAMES_PER_CHUNK * AUDIO_RECORDER_FRAME_BYTES)
#define MP3_CBR_BYTES_PER_SECOND             ((MP3_BITRATE_KBPS * 1000) / 8)
#define MP3_CBR_BYTES_PER_MP3_FRAME          ((72 * MP3_BITRATE_KBPS * 1000) / AUDIO_RECORDER_SAMPLE_RATE_HZ)
#define MP3_CBR_BYTES_PER_CHUNK              (MP3_CBR_BYTES_PER_MP3_FRAME * MP3_FRAMES_PER_CHUNK)          // 1152 for MP3_FRAMES_PER_CHUNK=4
#define MP3_CHUNK_DURATION_MS                ((MP3_PCM_FRAMES_PER_CHUNK * 1000) / AUDIO_RECORDER_SAMPLE_RATE_HZ)

// Ideal encrypted MP3 chunk sizing for this recorder configuration. Encrypt the
// actual CBR MP3 bytes from whole MP3 frames.
#define MP3_ENCRYPTED_PLAINTEXT_LENGTH       MP3_CBR_BYTES_PER_CHUNK
#define MP3_ENCRYPTED_CHUNK_LENGTH           (RECORDER_ENCRYPTED_CHUNK_NONCE_LENGTH + MP3_ENCRYPTED_PLAINTEXT_LENGTH + RECORDER_ENCRYPTED_CHUNK_TAG_LENGTH)
#define MP3_ENCRYPTED_BYTES_PER_SECOND       (MP3_CBR_BYTES_PER_SECOND + ((RECORDER_ENCRYPTED_CHUNK_OVERHEAD * 1000 + MP3_CHUNK_DURATION_MS - 1) / MP3_CHUNK_DURATION_MS))

#if defined(BUILD_USE_MP3_COMPRESSION)
#define AUDIO_RECORDER_PLAINTEXT_CHUNK_BYTES MP3_PCM_BYTES_PER_CHUNK
#else
#define AUDIO_RECORDER_PLAINTEXT_CHUNK_BYTES WAV_ENCRYPTED_AUDIO_PLAINTEXT_LENGTH
#endif

// strings can be parsed into one of these internally stored icons
enum : uint8_t
{
    ICON_UNKNOWN = 0,
    ICON_SMARTPHONE,
    ICON_LAPTOP,
    ICON_TABLET,
    ICON_HOME,
    ICON_WORK,
    ICON_CAR,
    ICON_PLANE,
    ICON_CAT,
    ICON_DOG,
    ICON_BIRD,
    ICON_CIRCLE,
    ICON_SQUARE,
    ICON_TRIANGLE,
    ICON_LAST
};

typedef enum
{
    MEMO_TYPE_NOTE = 0,
    MEMO_TYPE_TODO,
    MEMO_TYPE_JOURNAL,
    MEMO_TYPE_IDEA,
    MEMO_TYPE_REMINDER,
} MemoType;

#define WEBASSET_FILENAME_LEN 64
#define WEBASSET_MIMETYPE_LEN 64

typedef struct
{
    char file_name[WEBASSET_FILENAME_LEN];
    char mime_type[WEBASSET_MIMETYPE_LEN];
    uint32_t uncompressed_size;
    uint32_t compressed_size;
    const uint8_t* ptr_payload;
}
web_asset_desc_t;
