"""
Regenerate src/version.c before every build so compiler date/time macros refresh.
"""

from pathlib import Path
import subprocess

Import("env")

project_dir = Path(env["PROJECT_DIR"])
version_source = project_dir / "src" / "version.c"

def remove_stale_version_objects():
    build_dir = project_dir / ".pio" / "build"
    if not build_dir.is_dir():
        return

    for env_dir in build_dir.iterdir():
        if not env_dir.is_dir():
            continue

        for stale_file in (env_dir / "src" / "version.c.o", env_dir / "src" / "version.c.d"):
            try:
                stale_file.unlink()
            except FileNotFoundError:
                pass

def git_text(*args):
    try:
        return subprocess.check_output(
            ["git", *args],
            cwd=project_dir,
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return None

def c_string(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')

git_version = git_text("describe", "--exact-match", "--tags", "HEAD")
if not git_version:
    git_version = git_text("rev-parse", "--short=8", "HEAD")

version_string = f'"{c_string(git_version)}"' if git_version else '"Built " __DATE__ " " __TIME__'

content = f"""/* Auto-generated by tools/generate_version_source.py.
   Keep declarations in inc/thefly_version.h. */
#include "thefly_version.h"

#define THEFLY_STRINGIFY_VALUE(value) #value
#define THEFLY_STRINGIFY(value) THEFLY_STRINGIFY_VALUE(value)

#if defined(__clang__)
#define THEFLY_COMPILER_VERSION "Clang " __clang_version__
#elif defined(__GNUC__)
#define THEFLY_COMPILER_VERSION "GCC " __VERSION__
#elif defined(_MSC_VER)
#define THEFLY_COMPILER_VERSION "MSVC " THEFLY_STRINGIFY(_MSC_VER)
#else
#define THEFLY_COMPILER_VERSION "unknown compiler"
#endif

// Codex... why are you editing this file? Please don't edit this file... your tokens cost me real money.

const char* version_str = {version_string};
const char* compiler_version_str = THEFLY_COMPILER_VERSION;
const char* compiler_time_str = __DATE__ " " __TIME__;
"""

version_source.write_text(content, encoding="utf-8", newline="\r\n")
remove_stale_version_objects()
