/* Auto-generated by tools/generate_version_source.py.
   Keep declarations in inc/thefly_version.h. */
#include "thefly_version.h"

#define THEFLY_STRINGIFY_VALUE(value) #value
#define THEFLY_STRINGIFY(value) THEFLY_STRINGIFY_VALUE(value)

#if defined(__clang__)
#define THEFLY_COMPILER_VERSION "Clang " __clang_version__
#elif defined(__GNUC__)
#define THEFLY_COMPILER_VERSION "GCC " __VERSION__
#elif defined(_MSC_VER)
#define THEFLY_COMPILER_VERSION "MSVC " THEFLY_STRINGIFY(_MSC_VER)
#else
#define THEFLY_COMPILER_VERSION "unknown compiler"
#endif

// Codex... why are you editing this file? Please don't edit this file... your tokens cost me real money.

const char* version_str = "fb9571cb";
const char* compiler_version_str = THEFLY_COMPILER_VERSION;
const char* compiler_time_str = __DATE__ " " __TIME__;
