/* Auto-generated by tools/generate_version_source.py.
   build nonce: 1778869097914955500
   Keep declarations in inc/version.h. */
#include "version.h"

#define THEFLY_STRINGIFY_VALUE(value) #value
#define THEFLY_STRINGIFY(value) THEFLY_STRINGIFY_VALUE(value)

#if defined(__clang__)
#define THEFLY_COMPILER_VERSION "Clang " __clang_version__
#elif defined(__GNUC__)
#define THEFLY_COMPILER_VERSION "GCC " __VERSION__
#elif defined(_MSC_VER)
#define THEFLY_COMPILER_VERSION "MSVC " THEFLY_STRINGIFY(_MSC_VER)
#else
#define THEFLY_COMPILER_VERSION "unknown compiler"
#endif

const char* version_str = "The Fly firmware built " __DATE__ " " __TIME__;
const char* compiler_version_str = THEFLY_COMPILER_VERSION;
const char* compiler_time_str = __DATE__ " " __TIME__;
